name: 🔐 BackeerLoader Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: ⚙️ Theos o'rnatish (ldid'siz)
      run: |
        git clone --recursive https://github.com/theos/theos.git ~/theos
        
        # PATH
        echo "THEOS=~/theos" >> $GITHUB_ENV
        echo "~/theos/bin" >> $GITHUB_PATH

    - name: 🧹 Build (unsigned)
      run: |
        rm -rf .theos obj/
        make clean all LDFLAGS="-no-ldid"
      env:
        THEOS: ~/theos

    - uses: actions/upload-artifact@v4
      with:
        name: BackeerLoader-Unsigned
        path: .theos/obj/debug/BackeerLoader.dylib.unsigned
