name: 🔐 BackeerLoader Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: ⚙️ Theos + FIXED ldid
      run: |
        git clone --recursive https://github.com/theos/theos.git ~/theos
        
        # Theos'ning o'z ldid'si (eng ishonchli)
        git clone https://github.com/theos/sdks.git ~/theos/sdks
        cd ~/theos/sdks
        git checkout master
        
        # PATH
        echo "THEOS=~/theos" >> $GITHUB_ENV
        echo "~/theos/bin" >> $GITHUB_PATH

    - name: 🧹 Build
      run: |
        rm -rf .theos obj/
        make clean all
      env:
        THEOS: ~/theos

    - uses: actions/upload-artifact@v4
      with:
        name: BackeerLoader
        path: .theos/obj/debug/BackeerLoader.dylib
